### PR TITLE
fvp in 32 or 64bits

### PR DESCRIPTION
**Pull request by pascal-brand38**
Signed-off-by: Pascal Brand pascal.brand@st.com

### CODE REVIEW

**Comment by pascal-brand38** [comment]
Depends on https://github.com/OP-TEE/build/pull/48

**Comment by jforissier** [comment]
Since now all platforms can just set `CROSS_COMPILE` and it's enough, maybe we could get rid of the `CC_DIR` way?
In any case:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by pascal-brand38** [comment]
Right. I'll remove CC_DIR in another patch.

**Comment by pascal-brand38** [comment]
@jenswi-linaro @jbech-linaro Any other R-B or is it ok like this?

**Comment by jockebech** [comment]
This is all good, thanks for doing this change.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswikl** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
