### PR TITLE
Added platform MT8173 EVB

### PR DESCRIPTION
**Pull request by m943040028**
Signed-off-by: SY Chiu sy.chiu@linaro.org

### CODE REVIEW

**Comment by pascal-brand38** [comment]
@jenswi-linaro @vchong-linaro Who is merging in linaro-swg?

**Comment by jenswikl** [comment]
@pascal-brand-st-dev If you don't mind I think it would be good if you did.

**Comment by pascal-brand38** [comment]
@jenswi-linaro Sure, I'll do.

However, I do not feel comfortable reviewing this change, so if you can add a R-B tag. I'll then merge once the tag is added in the commit message.

**Comment by m943040028** [comment]
@pascal-brand-st-dev, does this patch has something wrong that let you not feel comfortable to review it? I will try to fix it.

**Comment by pascal-brand38** [comment]
@m943040028 Everything looks good to me. But I never really dig into this git, so I would prefer to have a more valuable opinion than mine.

**Comment by jenswikl** [comment]
@pascal-brand-st-dev thanks. What I'm after is that if we have only one that normally does the merging it's easier to have control over what gets merged. It's OK to depend on others to do the reviewing.

```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Pull request merged**
